// EJERCICIO 1
// DADO UN NUMERO DEVOLVER SU TABLA DE MULTIPLICAR DEL 1 AL 10

// EJERCICIO 2
// DADA UNA CADENA DE TEXTO, COMPROBAR SI LA PALABRA ES UN PALINDROMO
// (PALABRA QUE SE LEE IGUAL DE DERECHA A IZQUIERDA Y DE IZQUIERDA A DERECHA)

// EJERCICIO 3
// DADA UNA PALABRA, BUSCARLA EN UNA FRASE Y VERIFICAR LA CANTIDAD DE VECES QUE LA FRASE INCLUYE LA PALABRA

// TEXTO:
// "Hola mundo, este es el tercer ejercicio de programación. Me gusta la programación, es lo mejor del mundo"
