// EJERCICIO 1
// DADO UN NUMERO DEVOLVER SU TABLA DE MULTIPLICAR DEL 1 AL 10

// EJERCICIO 2
// DADA UNA CADENA DE TEXTO, COMPROBAR SI LA PALABRA ES UN PALINDROMO
// (PALABRA QUE SE LEE IGUAL DE DERECHA A IZQUIERDA Y DE IZQUIERDA A DERECHA)

// EJERCICIO 3
// DADA UNA PALABRA, BUSCARLA EN UNA FRASE Y VERIFICAR LA CANTIDAD DE VECES QUE LA FRASE INCLUYE LA PALABRA

// TEXTO:
// "Hola mundo, este es el tercer ejercicio de programación. Me gusta la programación, es lo mejor del mundo"

// EJERCICIO 4
// array = [1,2,3,4,5,6,7,8,9,10]
// DADO UN ARRAY, DEVOLVER UN ARRAY CON LOS ELEMENTOS MULTIPLOS DE 3

// EJERCICIO 5
// USANDO EL MISMO ARRAY (VALORES DE 0 A 10) RETORNAR LETRAS DEL ALFABETO EN LUGAR DE NUMEROS

// EJERCICIO 6
// HACER UNA FUNCION QUE SEA CALCULADORA DE PROPINA (LA PROPINA ES EL 10% DEL VALOR)
// LA FUNCION DEBE RECIBIR UN VALOR Y DEVOLVER EL VALOR DE LA PROPINA
// LA COMIDA TUVO UN COSTE DE $$$$ Y LA PROPINA FUE DE $$$$

// EJERCICIO 7
// TABLA DE MULTIPLICAR DINAMICA. QUIERE DECIR QUE LA FUNCION PUEDA RECIBIR UN NUMERO Y DEVOLVER
// LA TABLA DE MULTIPLICAR DEL MISMO

// FUNCION BLBLA (JSAHJSA JAHAJSAS) {
// AQUI DEVUELVE EL MAMBO
// LA TABLA DE MULTIPLICAR DEL "NUMERO" ES:
// AQUI LA TABLA -->
//}

//BLBLA(SAJHSAJAS JSAHSAJH)
